Fishconfig = { 
    { item = 'a_c_fishbluegil_01_ms', label = 'Blauer Sonnenbarsch (Medium)"' },
    { item = 'a_c_fishbluegil_01_sm', label = 'Blauer Sonnenbarsch (Klein)' },
    { item = 'a_c_fishbullheadcat_01_ms', label = 'Katzenwels (Medium)' },
    { item = 'a_c_fishbullheadcat_01_sm', label = 'Katzenwels (Klein)' },
    { item = 'a_c_fishchainpickerel_01_ms', label = 'Kettenhecht (Medium)' },
    { item = 'a_c_fishchainpickerel_01_sm', label = 'Kettenhecht (Klein)' },
    { item = 'a_c_fishchannelcatfish_01_lg', label = 'Kanalwels (Groß)' },
    { item = 'a_c_fishchannelcatfish_01_xl', label = 'Kanalwels (XL)' },
    { item = 'a_c_fishlakesturgeon_01_lg', label = 'Seestör' },
    { item = 'a_c_fishlargemouthbass_01_lg', label = 'Forellenbarsch (Groß)' },
    { item = 'a_c_fishlargemouthbass_01_ms', label = 'Forellenbarsch (Medium)' },
    { item = 'a_c_fishlongnosegar_01_lg', label = 'Gemeiner Knochenhecht' },
    { item = 'a_c_fishmuskie_01_lg', label = 'Muskellunge' },
    { item = 'a_c_fishnorthernpike_01_lg', label = 'Hecht' },
    { item = 'a_c_fishperch_01_ms', label = 'Flussbarsch (Medium)' },
    { item = 'a_c_fishperch_01_sm', label = 'Flussbarsch (Klein)' },
    { item = 'a_c_fishrainbowtrout_01_lg', label = 'Regenbogenforelle (Groß)' },
    { item = 'a_c_fishrainbowtrout_01_ms', label = 'Regenbogenforelle (Medium)' },
    { item = 'a_c_fishredfinpickerel_01_ms', label = 'Rotflossenhecht (Medium)' },
    { item = 'a_c_fishredfinpickerel_01_sm', label = 'Rotflossenhecht (Klein)' },
    { item = 'a_c_fishrockbass_01_ms', label = 'Steinbarsch (Medium)' },
    { item = 'a_c_fishrockbass_01_sm', label = 'Steinbarsch (Klein)' },
    { item = 'a_c_fishsalmonsockeye_01_lg', label = 'Rotlachs (Groß)' },
    { item = 'a_c_fishsalmonsockeye_01_ml', label = 'Rotlachs (Medium-Groß)' },
    { item = 'a_c_fishsalmonsockeye_01_ms', label = 'Rotlachs (Medium)' },
    { item = 'a_c_fishsmallmouthbass_01_lg', label = 'Kleinmaulbarsch (Groß)' },
    { item = 'a_c_fishsmallmouthbass_01_ms', label = 'Kleinmaulbarsch (Medium)' },
}
