FishConfig = {
    { item = 'a_c_fishbluegil_01_ms', label = 'Bluegill (Medium)' },
    { item = 'a_c_fishbluegil_01_sm', label = 'Bluegill (Small)' },
    { item = 'a_c_fishbullheadcat_01_ms', label = 'Bullhead Catfish (Medium)' },
    { item = 'a_c_fishbullheadcat_01_sm', label = 'Bullhead Catfish (Small)' },
    { item = 'a_c_fishchainpickerel_01_ms', label = 'Chain Pickerel (Medium)' },
    { item = 'a_c_fishchainpickerel_01_sm', label = 'Chain Pickerel (Small)' },
    { item = 'a_c_fishchannelcatfish_01_lg', label = 'Channel Catfish (Large)' },
    { item = 'a_c_fishchannelcatfish_01_xl', label = 'Channel Catfish (XL)' },
    { item = 'a_c_fishlakesturgeon_01_lg', label = 'Lake Sturgeon' },
    { item = 'a_c_fishlargemouthbass_01_lg', label = 'Largemouth Bass (Large)' },
    { item = 'a_c_fishlargemouthbass_01_ms', label = 'Largemouth Bass (Medium)' },
    { item = 'a_c_fishlongnosegar_01_lg', label = 'Longnose Gar' },
    { item = 'a_c_fishmuskie_01_lg', label = 'Muskie' },
    { item = 'a_c_fishnorthernpike_01_lg', label = 'Northern Pike' },
    { item = 'a_c_fishperch_01_ms', label = 'Perch (Medium)' },
    { item = 'a_c_fishperch_01_sm', label = 'Perch (Small)' },
    { item = 'a_c_fishrainbowtrout_01_lg', label = 'Rainbow Trout (Large)' },
    { item = 'a_c_fishrainbowtrout_01_ms', label = 'Rainbow Trout (Medium)' },
    { item = 'a_c_fishredfinpickerel_01_ms', label = 'Redfin Pickerel (Medium)' },
    { item = 'a_c_fishredfinpickerel_01_sm', label = 'Redfin Pickerel (Small)' },
    { item = 'a_c_fishrockbass_01_ms', label = 'Rock Bass (Medium)' },
    { item = 'a_c_fishrockbass_01_sm', label = 'Rock Bass (Small)' },
    { item = 'a_c_fishsalmonsockeye_01_lg', label = 'Sockeye Salmon (Large)' },
    { item = 'a_c_fishsalmonsockeye_01_ml', label = 'Sockeye Salmon (Medium-Large)' },
    { item = 'a_c_fishsalmonsockeye_01_ms', label = 'Sockeye Salmon (Medium)' },
    { item = 'a_c_fishsmallmouthbass_01_lg', label = 'Smallmouth Bass (Large)' },
    { item = 'a_c_fishsmallmouthbass_01_ms', label = 'Smallmouth Bass (Medium)' },
}
